frontend/accounts/urls.py
from django.urls import path
from frontend.accounts.views import RegisterView, LoginView, LogOutView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
]

frontend/project/urls.py
from django.urls import path, re_path
from frontend.project.views import ProjectListView, DashboardView, AddProjectView, EditProjectView

app_name = 'project'

urlpatterns = [
    path('all-projects/', ProjectListView.as_view(), name='all-projects'),
    path('add-project/', AddProjectView.as_view(), name='add-project'),
    re_path(r'^edit-project/(?P<pk>[0-9a-f-]+)/$', EditProjectView.as_view(), name='edit-project'),
    re_path(r'^dashboard/(?P<pk>[0-9a-f-]+)/$', DashboardView.as_view(), name='dashboard'),
]

frontend/task/urls.py
from django.urls import path, re_path
from frontend.task.views import TaskListView, AddTaskView, EditTaskView, SubTaskListView, DeleteTaskView

app_name = 'task'

urlpatterns = [
    path('all-tasks/', TaskListView.as_view(), name='all-tasks'),
    re_path(r'^sub-tasks/(?P<task_id>[0-9a-f-]+)/(?P<task_title>(.*))/$', SubTaskListView.as_view(), name='sub-tasks'),
    path('add-task/', AddTaskView.as_view(), name='add-task'),
    re_path(r'^project/(?P<project_id>[0-9a-f-]+)/edit-task/(?P<pk>[0-9a-f-]+)/$', EditTaskView.as_view(), name='edit-task'),
    re_path(r'^delete/(?P<pk>[0-9a-f-]+)/$', DeleteTaskView.as_view(), name='delete-task'),
]

ufaber_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from ufaber_assignment.settings import MEDIA_ROOT, MEDIA_URL
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    # admin URLs
    path('admin/', admin.site.urls),

    # Login URL
    path('', TemplateView.as_view(template_name='accounts/login.html'), name='login'),

    # other include URLs
    path('accounts/', include('frontend.accounts.urls'), name='accounts'),
    path('project/', include('frontend.project.urls'), name='project'),
    path('task/', include('frontend.task.urls'), name='task'),

    path('api/accounts/', include('backend.api_accounts.urls'), name='api-accounts'),
    path('api/project/', include('backend.api_project.urls'), name='api-project'),
    path('api/task/', include('backend.api_task.urls'), name='api-task'),


    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

frontend/project/models.py
from django.db import models

# Create your models here.

frontend/project/views.py
from django.views.generic import TemplateView
from ufaber_assignment.settings import DOMAIN
import requests
from django.shortcuts import reverse, redirect
from backend.api_task.models import PENDING, IN_PROCESS
from django.contrib import messages
from frontend.utils import process_json_response


class ProjectListView(TemplateView):
    template_name = 'project/projects.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)

        # projects API call
        project_url = '{0}/api/project/project-crud/'.format(DOMAIN)
        headers = {'Authorization': 'Bearer {0}'.format(request.session.get('access_token'))}
        project_response = requests.get(url=project_url, headers=headers)
        if project_response.status_code == 200:
            # user init API call
            user_url = '{0}/api/accounts/user-init/'.format(DOMAIN)
            user_response = requests.get(url=user_url, headers=headers)
            if user_response.status_code == 200:
                user_response_json = user_response.json()
                request.session['user_details'] = user_response_json
            else:
                return process_json_response(request=request, response=user_response)

            projects = project_response.json()['results']
            context['projects'] = projects
            if len(projects) == 0:
                return redirect(reverse('project:add-project'))
            return self.render_to_response(context)
        else:
            return process_json_response(request=request, response=project_response)


class AddProjectView(TemplateView):
    template_name = 'project/add-edit-project.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'A'
        return context

    def post(self, request, *args, **kwargs):
        url = '{0}/api/project/project-crud/'.format(DOMAIN)
        headers = {'Authorization': 'Bearer {0}'.format(request.session.get('access_token'))}
        response = requests.post(url=url, data=request.POST, files=request.FILES, headers=headers)
        if response.status_code == 201:
            messages.success(request, 'Project added successfully')
            return redirect(reverse('project:dashboard', kwargs={'pk': response.json()['id']}))
        else:
            return process_json_response(request=request, response=response)


class EditProjectView(TemplateView):
    template_name = 'project/add-edit-project.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'E'
        return context

    def get(self, request, *args, **kwargs):
        project_id = kwargs.get('pk')
        context = self.get_context_data(**kwargs)
        url = '{0}/api/project/project-crud/{1}/'.format(DOMAIN, project_id)
        headers = {'Authorization': 'Bearer {0}'.format(request.session.get('access_token'))}
        response = requests.get(url=url, headers=headers)
        if response.status_code == 200:
            project = response.json()
            context['project'] = project
        else:
            return process_json_response(request=request, response=response)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        request.POST._mutable = True
        if 'avatar' in request.POST.keys():
            request.POST.pop('avatar')
        project_id = kwargs.get('pk')
        url = '{0}/api/project/project-crud/{1}/'.format(DOMAIN, project_id)
        headers = {'Authorization': 'Bearer {0}'.format(request.session.get('access_token'))}
        response = requests.patch(url=url, data=request.POST, files=request.FILES, headers=headers)
        if response.status_code == 200:
            messages.success(request, 'Project edited successfully')
            return redirect(reverse('project:all-projects'))
        else:
            return process_json_response(request=request, response=response)


class DashboardView(TemplateView):
    template_name = 'project/dashboard.html'

    def get(self, request, *args, **kwargs):
        project_id = kwargs.get('pk')
        request.session['project_id'] = project_id
        context = self.get_context_data(**kwargs)
        url = '{0}/api/project/dashboard-api/?project_id={1}'.format(DOMAIN, project_id)
        headers = {'Authorization': 'Bearer {0}'.format(request.session.get('access_token'))}
        response = requests.get(url=url, headers=headers)
        if response.status_code == 200:
            response_json = response.json()
            task_status_data = response_json['task_status_data'][0] if response_json['task_status_data'] else []
            project_data = response_json['project_data']

            context['task_status_data'] = task_status_data
            context['project_data'] = project_data
            context['tasks_data'] = response_json['tasks_data']
            context['PENDING'] = PENDING
            context['IN_PROCESS'] = IN_PROCESS
            request.session['project_name'] = project_data['name']
        else:
            return process_json_response(request=request, response=response)
        return self.render_to_response(context)

frontend/project/templates/project/add-edit-project.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Projects</title>
    {% include 'frontend/html_includes/main-css.html' %}
</head>

<body class="hold-transition layout-top-nav">
<div class="wrapper">
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">{% if type == 'A' %}Add{% elif type == 'E' %}Edit{% endif %} Project</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="javascript:void(0)" onclick="window.history.back()" class="btn btn-secondary mr-3">Back</a>
                        <a href="{% url 'accounts:logout' %}" class="btn btn-default mr-3">Logout</a>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-7">
                        <div class="card card-primary">
                            <form id="id_add_edit_project_form"
                                  action="{% if type == 'A' %}{% url 'project:add-project' %}{% elif type == 'E' %}{% url 'project:edit-project' pk=project.id %}{% endif %}"
                                  method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% if type == 'A' %}
                                    <input type="hidden" value="{{ request.session.user_details.id }}" name="owner">
                                {% endif %}
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="id_project_name">Name</label>
                                        <input type="text" class="form-control" name="name" id="id_project_name" value="{% if type == 'E' %}{{ project.name }}{% endif %}" autocomplete="off" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_project_description">Description</label>
                                        <textarea class="form-control" name="description" id="id_project_description" cols="30" rows="4" required>{% if type == 'E' %}{{ project.description }}{% endif %}</textarea>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_project_date_of_completion">Completion Date</label>
                                        <input type="date" class="form-control" name="date_of_completion" id="id_project_date_of_completion" value="{% if type == 'E' %}{{ project.date_of_completion }}{% endif %}" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="id_project_avatar">Avatar</label> <br/>
                                        <input type="file" id="id_project_avatar" name="avatar" accept="image/*" {% if type == 'A' %}required{% endif %}>
                                        {% if type == 'E' %}
                                            <div class="mt-4">
                                                <a target="_blank" href="{{ project.avatar }}">
                                                    <img width="20%" src="{{ project.avatar }}" alt="{{ project.name }}">
                                                </a>
                                            </div>
                                        {% endif %}
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <button type="button" onclick="formSubmitCommonFunction($(this))" class="btn btn-primary">Submit</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    {% include 'frontend/html_includes/footer.html' %}

</div>
{% include 'frontend/html_includes/main-js.html' %}
<script>

    var rules = {
        name: {required: true},
        description: {required: true},
    };
    common_form_validation_fn($('#id_add_edit_project_form'), rules, 'form-group');
</script>
</body>
</html>

frontend/project/templates/project/dashboard.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Dashboard</title>
    {% include 'frontend/html_includes/main-css.html' %}
</head>
<body class="hold-transition layout-top-nav">
<div class="wrapper">
    {% include 'frontend/html_includes/top-menu.html' %}
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">{{ project_data.name }} - Dashboard</h1>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="container">
                {% if task_status_data|length > 0 %}
                    <div class="row">
                        <div class="col-lg-2 col-6">
                            <div class="small-box bg-danger">
                                <div class="inner">
                                    <h3>{{ task_status_data.total_in_process }}</h3>
                                    <p>Tasks In Process</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-pie-graph"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-6">
                            <div class="small-box bg-warning">
                                <div class="inner">
                                    <h3>{{ task_status_data.total_pending }}</h3>
                                    <p>Tasks Pending</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-person-add"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-6">
                            <div class="small-box bg-success">
                                <div class="inner">
                                    <h3>{{ task_status_data.total_completed }}</h3>
                                    <p>Tasks Completed</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2 col-6">
                            <div class="small-box bg-secondary">
                                <div class="inner">
                                    <h3>{{ task_status_data.total_tasks }}</h3>
                                    <p>Total Tasks</p>
                                </div>
                                <div class="icon">
                                    <i class="ion ion-stats-bars"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
                <div class="row mt-3">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Recently Added Tasks</h3>
                            </div>
                            <div class="card-body table-responsive p-0">
                                {% if tasks_data|length > 0 %}
                                    <table class="table table-hover text-nowrap">
                                        <thead>
                                            <tr>
                                                <th>Title</th>
                                                <th>Start Date</th>
                                                <th>End Date</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for task in tasks_data %}
                                                <tr>
                                                    <td>{{ task.title }}</td>
                                                    <td >{{ task.start_date|date_format }}</td>
                                                    <td>{{ task.end_date|date_format }}</td>
                                                    <td class="{% if task.status == PENDING %}text-warning{% elif task.status == IN_PROCESS %}text-danger{% endif %}">{{ task.status }}</td>
                                                    <td><a href="{% url 'task:edit-task' project_id=request.session.project_id pk=task.id %}?tt=1">Open</a></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                {% else %}
                                    <h5 class="text-center m-3">No tasks added. <a href="{% url 'task:add-task' %}">Add Now</a></h5>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <!-- /.content-wrapper -->
    {% include 'frontend/html_includes/footer.html' %}
</div>

{% include 'frontend/html_includes/main-js.html' %}
</body>
</html>

frontend/project/templates/project/projects.html
{% load static %}
{% load custom_filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Projects</title>
    {% include 'frontend/html_includes/main-css.html' %}
</head>

<body class="hold-transition layout-top-nav">
<div class="wrapper">
    <div class="content-wrapper">
        <div class="content-header">
            <div class="container">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0">Select a project to proceed</h1>
                    </div>
                    <div class="col-sm-6 text-right">
                        <a href="javascript:void(0)" onclick="window.history.back()" class="btn btn-secondary mr-3">Back</a>
                        <a href="{% url 'project:add-project' %}" class="btn btn-primary mr-3">Add Project</a>
                        <a href="{% url 'accounts:logout' %}" class="btn btn-default mr-3">Logout</a>
                    </div>
                </div>
            </div>
        </div>
        <section class="content">
            <div class="container">
                <div class="row d-flex align-items-stretch">
                    {% for project in projects %}
                        <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch p-3">
                            <div class="card bg-light">
                                <div class="card-header text-muted border-bottom-0"></div>
                                <div class="card-body pt-0">
                                    <div class="row">
                                        <div class="col-7">
                                            <h2 class="lead"><b>{{ project.name }}</b></h2>
                                            <p class="text-muted text-sm"><b>About: </b>{{ project.description }}</p>
                                            <ul class="ml-0 mb-0 fa-ul text-muted">
                                                <li class="small">Completion Date: {{ project.date_of_completion|date_format }}</li>
                                                <li class="small">Owner: {{ project.owner.first_name }} {{ project.owner.last_name }}</li>
                                            </ul>
                                        </div>
                                        <div class="col-5 text-center">
                                            <img src="{{ project.avatar }}" alt="user-avatar" class="img-fluid">
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <div class="text-right">
                                        <a href="{% url 'project:edit-project' pk=project.id %}" class="btn btn-sm btn-default float-left">Edit</a>
                                        <a href="{% url 'project:dashboard' pk=project.id %}" class="btn btn-sm btn-success text-left">Open</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
    {% include 'frontend/html_includes/footer.html' %}

</div>
{% include 'frontend/html_includes/main-js.html' %}

</body>
</html>