frontend/accounts/urls.py
from django.urls import path
from frontend.accounts.views import RegisterView, LoginView, LogOutView

app_name = 'accounts'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogOutView.as_view(), name='logout'),
]

ufaber_assignment/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.conf.urls.static import static
from ufaber_assignment.settings import MEDIA_ROOT, MEDIA_URL
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    # admin URLs
    path('admin/', admin.site.urls),

    # Login URL
    path('', TemplateView.as_view(template_name='accounts/login.html'), name='login'),

    # other include URLs
    path('accounts/', include('frontend.accounts.urls'), name='accounts'),
    path('project/', include('frontend.project.urls'), name='project'),
    path('task/', include('frontend.task.urls'), name='task'),

    path('api/accounts/', include('backend.api_accounts.urls'), name='api-accounts'),
    path('api/project/', include('backend.api_project.urls'), name='api-project'),
    path('api/task/', include('backend.api_task.urls'), name='api-task'),


    path('api/token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

frontend/accounts/models.py
from django.db import models

# Create your models here.

frontend/accounts/views.py
from django.shortcuts import redirect, reverse
from django.views.generic import TemplateView
from ufaber_assignment.settings import DOMAIN
import requests
from django.contrib import messages
from django.contrib.auth import logout
from frontend.utils import process_json_response


class RegisterView(TemplateView):
    template_name = 'accounts/register.html'

    def post(self, request, *args, **kwargs):
        url = '{0}/api/accounts/user-create/'.format(DOMAIN)
        response = requests.post(url=url, data=request.POST)
        if response.status_code == 201:
            messages.success(request, 'Registered successfully')
            return redirect(reverse('accounts:login'))
        else:
            return process_json_response(request=request, response=response)


class LoginView(TemplateView):
    template_name = 'accounts/login.html'

    def post(self, request, *args, **kwargs):
        url = '{0}/api/token/'.format(DOMAIN)
        response = requests.post(url=url, data=request.POST)
        if response.status_code == 200:
            request.session['access_token'] = response.json()['access']
            return redirect(reverse('project:all-projects'))
        else:
            messages.error(request, response.json()['detail'])
            return redirect(reverse('accounts:login'))


class LogOutView(TemplateView):
    template_name = 'accounts/logout.html'

    def get(self, request, *args, **kwargs):
        logout(request=request)
        return super().get(request, *args, **kwargs)

frontend/accounts/templates/accounts/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Log in</title>
    {% include 'frontend/html_includes/main-css.html' %}
</head>

<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="javascript:void(0)"><strong>Task App</strong></a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Log in to your account</p>
            <form id="login-form" action="{% url 'accounts:login' %}" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" name="username" id="id_username" class="form-control" placeholder="Username">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-5">
                    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password">
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-12">
                        <button type="button" class="btn btn-primary btn-block" onclick="formSubmitCommonFunction($(this))">Log In</button>
                    </div>
                </div>
            </form>

            <p class="mb-0"><a href="{% url 'accounts:register' %}" class="text-center">Create a new account</a></p>
        </div>
    </div>
</div>
{% include 'frontend/html_includes/main-js.html' %}
<script>

    var rules = {
        username: {required: true,},
        password: {required: true,}
    };
    common_form_validation_fn($('#login-form'), rules, 'input-group');
</script>
</body>
</html>

frontend/accounts/templates/accounts/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Refresh" content="2; url={% url 'accounts:login' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Log in</title>
    {% include 'frontend/html_includes/main-css.html' %}
</head>

<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <strong>Successfully Logged Out</strong>
    </div>
    <div class="text-center">
        <a href="{% url 'accounts:login' %}">Login</a>
    </div>
</div>
{% include 'frontend/html_includes/main-js.html' %}
</body>
</html>

frontend/accounts/templates/accounts/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Register</title>

    {% include 'frontend/html_includes/main-css.html' %}
</head>

<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="javascript:void(0)"><strong>Task App</strong></a>
    </div>
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">Register to create an account</p>
            <form id="register-form" action="{% url 'accounts:register' %}" method="POST">
                {% csrf_token %}
                <div class="input-group mb-3">
                    <input type="text" name="username" id="id_username" class="form-control" placeholder="Username" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" name="first_name" id="id_first_name" class="form-control" placeholder="First Name" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="text" name="last_name" id="id_last_name" class="form-control" placeholder="Last Name" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-3">
                    <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="input-group mb-5">
                    <input type="password" name="password2" id="id_password2" class="form-control" placeholder="Confirm Password" required>
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-12">
                        <button type="button" onclick="formSubmitCommonFunction($(this))" class="btn btn-primary btn-block">Register</button>
                    </div>
                </div>
            </form>

            <p class="mb-0"><a href="{% url 'login' %}" class="text-center">Already have an account</a></p>
        </div>
    </div>
</div>

{% include 'frontend/html_includes/main-js.html' %}
<script>
    $.validator.addMethod('password_equal', function(value, element) {
        return $('#id_password').val() === $('#id_password2').val();
    }, "The two passwords does not match");

    var rules = {
        username: {required: true,},
        first_name: {required: true,},
        last_name: {required: true,},
        password: {
            required: true,
            minlength: 8,
            password_equal: true
        },
        password2: {
            required: true,
            minlength: 8,
            password_equal: false
        }
    };

    common_form_validation_fn($('#register-form'), rules, 'input-group');

</script>
</body>
</html>